#!/bin/sh

if [ $# -lt 2 ]; then
	echo "Usage: guest_asm FILE FUNC"
	exit 1
fi

if [ "$2" = "guest" ]; then
	objdump -D -b binary -m i8086 $1
else
	objdump -b binary -m i8086 --disassemble="$2" $1
fi


