#!/bin/sh

if [ $# -lt 2 ]; then
	echo "Usage: guest_asm FILE FUNC"
	exit 1
fi

ARCH="i386"
if [ "$2" = "guest" ]; then
	ARCH="i8086"
fi

gdb --batch -ex "set architecture $ARCH" -ex "disassemble $2" $1
